kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: application
  name: chaos-monkey
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "delete"]