kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: workloads
  name: chaos-monkey
  labels:
    name: pod-chaos-monkey
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
  