apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaos-monkey-workloads
  labels:
    name: pod-chaos-monkey
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chaos-monkey
subjects:
- kind: ServiceAccount
  name: default
  namespace: workloads
  