apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
 # Service name
 name: service-chaos-monkey
spec:
 selector:
   # Selector for Pods
   app: pod-chaos-monkey
 ports:
   # Port Map
 - port: 80
   targetPort: 3000
   protocol: TCP
 type: LoadBalancer